### ISSUE TITLE
I want to help

### ISSUE THREAD

**Issue by Niyant1** [PrakharPythonProgrammer/Grail-0.6#10]
Hi Everyone.,My name is Niyant. I am here to help you for updating of browser.... I hope I can give my best...
I am person of brain storming  ideas and I have experience of  begginer in python... So I hope you don't mind it and helping each other here will be key feature of here... And believe me I can give you so woowwwww!!!!! Ideas that you have never thought or ever imagined....
I am ending with this for a new start of new Journey.... And I am thankful to GVR sir  and originator PPP..... Thank you for understanding me and feeling I am useful too you

**Comment by PrakharPythonProgrammer** [comment]
Thanks
