### ISSUE TITLE
What is this At ?

### ISSUE THREAD

**Issue by PrakharPythonProgrammer** [PrakharPythonProgrammer/Grail-0.6#11]
I am changing the files according to Python 3 and this At appears many times ? What is this At ? Is it a class(I'm guessing because of naming convention rule) or is it function(less chance I think) ? And what is the alternative for this in Python 3 ?

**Comment by PrakharPythonProgrammer** [comment]
This is one example where it is used - self.__viewer.text.index(At(event.x, event.y))
Location - inside main directory with the file name GrailHTMLParser.py

**Comment by vadmium** [comment]
Looks like that came from the "from Tkinter import * " line. It was removed in 3.4: <https://bugs.python.org/issue3035>.

**Comment by PrakharPythonProgrammer** [comment]
I also have thought that it came from tkinter but u wasn't sure.

**Comment by PrakharPythonProgrammer** [comment]
What is the use of it ? Do you know ?

**Comment by PrakharPythonProgrammer** [comment]
@vadmium do you know the use of At and it's alternative for Python 3 ?

**Comment by vadmium** [comment]
The bug thread I linked leads to another bug with this change that removed the code: <https://hg.python.org/cpython/rev/83da5729e362#l2.37>. I would try defining the function using that deleted code in the Grail code, or adapting the code to convert the arguments some other way, depending on how widespread the problem is.

**Comment by PrakharPythonProgrammer** [comment]
Ok I'll check the bug thread.
Are you making the string module changes ?

**Comment by PrakharPythonProgrammer** [comment]
I have seen the thread. I'll define my own At function and write the code
given in it. This way I'll be able to access the At function. Thanks a lot
for the help. I was really stuck in this At function
