### ISSUE TITLE
UndefinedStyle

### ISSUE THREAD

**Issue by PrakharPythonProgrammer** [PrakharPythonProgrammer/Grail-0.6#4]
I have searched on internet and as far as my knowledge there is no exception like UndefinedStyle. Can you tell @gvanrossum what kind of error did you want it to handle ? Maybe the name for that exception is changed.

**Comment by gvanrossum** [comment]
It's an exception defined in Stylesheet.py. In Python 1, exceptions were just string literals.

**Comment by PrakharPythonProgrammer** [comment]
That means we cannot use it in Python 3 ?

**Comment by gvanrossum** [comment]
No, you just change this line:
```
UndefinedStyle = 'UndefinedStyle'
```
into this:
```
class UndefinedStyle(Exception):
    pass
```

**Comment by PrakharPythonProgrammer** [comment]
Okay I got it we are inheriting the Exception class which is the base class
of every exception.
