### ISSUE TITLE
I would like to help

### ISSUE THREAD

**Issue by hridaya423** [PrakharPythonProgrammer/Grail-0.6#6]
I would like to help

**Comment by PrakharPythonProgrammer** [comment]
Thank you for your help. The syntax errors are fixed. Now the imports and
data types are left. I hope you know about importing packages. If yes then
download the code in the gihub repo and fix the errors in your local
machine. After the changes are made then commit those changes in the repo.

Sincerely
Prakhar

**Comment by hridaya423** [comment]
Sure, Thanks!

**Comment by PrakharPythonProgrammer** [comment]
Hi @hridaya423 you said you would like to help ? But there has been no response from your side. This is a huge project so we need as much help as possible. We would really appreciate your help.

Sincerely
Prakhar

**Comment by hridaya423** [comment]
Hi, Prakhar
I was busy with some exams, will do surely..

**Comment by PrakharPythonProgrammer** [comment]
Ok no problem
