### ISSUE TITLE
Replace usages of "string" module

### ISSUE THREAD

**Issue by notatallshaw** [PrakharPythonProgrammer/Grail-0.6#8]
I was taking a look to see if I could help and it became clear there are several transformations that need to be applied across the whole code base before being able to work on individual files.

The first thing I notice compared to Python 3 is the "string" module which appears to refer to a module that was available in Python 1 and 2 but not in 3: https://docs.python.org/release/1.4/lib/node49.html

Doing a naive search through the code bade I found the following methods exceptions being used and I've listed their replacements:

```
string.capitalize -> str.capitalize 
string.capwords -> str.title
string.splitfields -> str.split
string.upper -> str.upper
string.lstrip -> str.lstrip
string.replace -> str.replace
string.joinfields -> str.join
string.atol -> int
string.rfind -> str.rfind
string.lower -> str.lower
string.whitespace -> string.whitespace
string.split -> str.split
string.atoi -> int
string.digits -> string.digits
string.maketrans -> str.maketrans
string.rstrip -> str.rstrip
string.index -> str.index
string.atof -> float
string.strip -> str.strip
string.translate -> str.translate
string.find -> str.find
string.join -> str.join
```

I also found the following exceptions which all look like they can be replaced with `ValueError`:
```
string.atof_error
string.atoi_error
string.atol_error
```

I am preparing a PR with the following steps:

1. Find any case where a name is bound to the built-in `str`, and change the name to `str_`
2. Replace the above methods
3. Replace the above exceptions

I plan to automate the bulk of the replacements and I don't have any test cases to prove it's the correct approach as the code base itself does not run. So let me know if there's any preferred other way you think this should be approached.

**Comment by PrakharPythonProgrammer** [comment]
Thanks for pointing out that Damian what you want to do is correct but your
approach may be wrong because I had experience like this before I used find
and replace and it replaced some things which i didn't want so I think find
and replace is not a good method. But if you want to do that make sure you
find and replace with accuracy make sure it replaces the exact words and
not the words similar to that.

Sincerely
Prakhar

**Comment by notatallshaw** [comment]
I am writing a fairly naive Python script to handle the majority of the cases and then handwriting the cases where the name "string" is imported in any more complicated way than "import string", e.g. "from string import join" or "from . import string".

A better approach would be to write a script which builds an AST of the old code, transforms it, and then writes the new AST back to Python 3. But I certainly don't have the resources to do that right now.

Let me know if you think my approach is not going to be strong enough to be worthwhile submitting a PR.

**Comment by vadmium** [comment]
This commit I did several years ago might be what you are trying to do: <https://github.com/vadmium/grailbrowser/commit/96011fa>

**Comment by PrakharPythonProgrammer** [comment]
I think creating a script and all that for handling is a difficult task.
One more thing don't remove all places where string is used just remove for
ex string.atoi etc. In short those which are deprecated since Python 3.
atoi should be replaced with int and atof with float

**Comment by notatallshaw** [comment]
@vadmium Yeah I agree that looks like a lot of the work has actually already been done to get it from Python 1 to 2.

Actually speaking of which, it seems it would be considerably easier to try and get this project running under Python 2 and then run Python 2to3 to a lot of the heavy lifting to get it to Python 3.

**Comment by PrakharPythonProgrammer** [comment]
Thanks, this is what we wanted to do.

**Comment by PrakharPythonProgrammer** [comment]
I think we should try to work on Grail Browser which is made compatible
with Python 3.3. This way the transition will be easy

**Comment by notatallshaw** [comment]
Okay, seems others have already done a lot of the required work here. I am not going to duplicate those efforts in a worse way. Should cherry pick from other repos or re-implement their approach here.

**Comment by PrakharPythonProgrammer** [comment]
I was seeing the files which @vadmium created and there are very few errors in it so I think we should work on that instead of the transition from Python 1 to Python 3 because it's a difficult task. What are your opinions ?

**Comment by PrakharPythonProgrammer** [comment]
@notatallshaw are you working on those string modules changes ?

**Comment by notatallshaw** [comment]
Nope, @vadmium has already done a better job of it than I would have done. As they actually use the methods directly on the literal rather than just replacing the "string" module look-up with a "str" builtin look-up. I don't see any reason to duplicate the effort but not as good.

**Comment by PrakharPythonProgrammer** [comment]
Ok but there are many other places where the modules need to be changed. If
you're interested in this project than I hope you'll find many other places
where changes are needed.

**Comment by notatallshaw** [comment]
The problem with contributing right now is there is no structure or guidelines on what is trying to be achieved and how to go about doing it. I think you should pin an issue answering questions like (but not limited to):

1. What specific version of Python is being targeted?
2. Is the project trying to create a faithful implementation of the existing code but just on a different Python version or is it trying to make improvements to the code?
3. What are the top things that need to be worked on? Or a priority list of work?
4. Are you looking for systemic changes or should people work on fixing individual files?

I picked the `string` issue as I saw it was a relatively straightforward issue and as long as the project is targeting any version of Python 3 it didn't really matter the answer to most of these questions.

But lots of issues are less straightforward and require guidance.

**Comment by PrakharPythonProgrammer** [comment]
Thanks for pointing out that you are right there should be some structure
and I'll be honest I am a little new to GitHub so the way I am doing things
may not be the best way to do it but I'll try my best. And I'll create an
issue as you suggested which will answer questions like what's the goal,
which version is it targeting etc. Feel free to tell any other problems you
face while contributing to this project.
