### ISSUE TITLE
Some files seem to be missing

### ISSUE THREAD

**Issue by PrakharPythonProgrammer** [PrakharPythonProgrammer/Grail-0.6#9]
I haven't checked each and every folder so I don't know the total number but some files seem to be missing like grail.py
Why did you delete those @vadmium ?

**Comment by vadmium** [comment]
It's a long time ago. I remember I wanted the code loadable from an external module, so I moved everything under a "grail" subdirectory. If "grail.py" was the script to start it, maybe try running "python grail" or "python -m grail" from the top level to run the package's __main__.py as a script.

**Comment by PrakharPythonProgrammer** [comment]
Oh! ok I'll try that
